
    class Box_East_Ammo_F; // CUP_RUBasicAmmunitionBox
    class Box_NATO_Ammo_F; // CUP_USBasicAmmunitionBox
    class Box_East_Wps_F; // CUP_RUBasicWeaponsBox
    class Box_NATO_Wps_F; // CUP_USBasicWeaponsBox
    class Box_East_Support_F; // CUP_RUSpecialWeaponsBox
    class Box_NATO_Support_F; // CUP_USSpecialWeaponsBox
    class Box_East_WpsLaunch_F; // CUP_RULaunchersBox
    class Box_NATO_WpsLaunch_F; // CUP_USLaunchersBox
    // class Box_East_Uniforms_F; // CUP_RUBasicWeaponsBox
    class Box_NATO_Uniforms_F; // CUP_USBasicWeaponsBox
    class O_SupplyCrate_F; // CUP_RUVehicleBox
    class B_SupplyCrate_F; // CUP_USVehicleBox

    class IND_EUDF35_F_AmmoBox : Box_NATO_Ammo_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Ammo Box;
        class TransportMagazines {
            mag_xx(30Rnd_65x39_caseless_msbs_mag,50);
            mag_xx(Chemlight_blue,50);
            mag_xx(16Rnd_9x21_Mag,50);
            mag_xx(HandGrenade,50);
            mag_xx(SmokeShell,50);
            mag_xx(SatchelCharge_Remote_Mag,50);
            mag_xx(DemoCharge_Remote_Mag,50);
            mag_xx(APERSBoundingMine_Range_Mag,50);
            mag_xx(APERSMine_Range_Mag,50);
            mag_xx(ClaymoreDirectionalMine_Remote_Mag,50);
            mag_xx(SLAMDirectionalMine_Wire_Mag,50);
            mag_xx(30Rnd_9x21_Mag_SMG_02,50);
            mag_xx(SmokeShellBlue,50);
            mag_xx(SmokeShellPurple,50);
            mag_xx(SmokeShellOrange,50);
            mag_xx(MiniGrenade,50);
            mag_xx(1Rnd_HE_Grenade_shell,50);
            mag_xx(MRAWS_HEAT_F,50);
            mag_xx(200Rnd_65x39_cased_Box,50);
            mag_xx(Titan_AA,50);
            mag_xx(150Rnd_93x64_Mag,50);
            mag_xx(Titan_AT,50);
            mag_xx(1Rnd_Smoke_Grenade_shell,50);
            mag_xx(1Rnd_SmokeGreen_Grenade_shell,50);
            mag_xx(1Rnd_SmokeOrange_Grenade_shell,50);
            mag_xx(1Rnd_SmokePurple_Grenade_shell,50);
            mag_xx(SmokeShellGreen,50);
            mag_xx(30Rnd_65x39_caseless_msbs_mag_Tracer,50);
            mag_xx(I_IR_Grenade,50);
            mag_xx(1Rnd_SmokeBlue_Grenade_shell,50);
            mag_xx(APERSMineDispenser_Mag,50);
            mag_xx(APERSTripMine_Wire_Mag,50);
            mag_xx(20Rnd_762x51_Mag,50);
            mag_xx(ATMine_Range_Mag,50);
            mag_xx(30Rnd_556x45_Stanag_green,50);
            mag_xx(11Rnd_45ACP_Mag,50);
            mag_xx(NLAW_F,50);
            mag_xx(150Rnd_556x45_Drum_Mag_F,50);
            mag_xx(30Rnd_556x45_Stanag_Tracer_Green,50);
            mag_xx(Laserbatteries,50);
            mag_xx(SmokeShellYellow,50);
            mag_xx(6Rnd_12Gauge_Pellets,50);
            mag_xx(5Rnd_127x108_Mag,50);
            mag_xx(Chemlight_yellow,50);
            mag_xx(30Rnd_556x45_Stanag,50);
            mag_xx(20Rnd_556x45_UW_mag,50);
            mag_xx(30Rnd_556x45_Stanag_red,50);
        };
        class TransportWeapons {
        };
        class TransportItems {
        };
    };
    class IND_EUDF35_F_WeaponsBox : Box_NATO_Wps_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Weapons Box;
        class TransportMagazines {
            mag_xx(30Rnd_65x39_caseless_msbs_mag,50);
            mag_xx(16Rnd_9x21_Mag,50);
            mag_xx(30Rnd_9x21_Mag_SMG_02,50);
            mag_xx(200Rnd_65x39_cased_Box,50);
            mag_xx(1Rnd_HE_Grenade_shell,50);
            mag_xx(150Rnd_93x64_Mag,50);
            mag_xx(20Rnd_762x51_Mag,50);
            mag_xx(30Rnd_556x45_Stanag_green,50);
            mag_xx(11Rnd_45ACP_Mag,50);
            mag_xx(150Rnd_556x45_Drum_Mag_F,50);
            mag_xx(6Rnd_12Gauge_Pellets,50);
            mag_xx(5Rnd_127x108_Mag,50);
            mag_xx(20Rnd_556x45_UW_mag,50);
        };
        class TransportWeapons {
            weap_xx(arifle_MSBS65_EUDF35_arco_pointer_snds_F,10);
            weap_xx(hgun_P07_blk_F,10);
            weap_xx(arifle_MSBS65_EUDF35_aco_pointer_F,10);
            weap_xx(arifle_MSBS65_EUDF35_aco_pointer_snds_F,10);
            weap_xx(SMG_05_EUDF35_aco_pointer_F,10);
            weap_xx(LMG_Mk200_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_GL_EUDF35_arco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_Mark_EUDF35_dms_pointer_snds_bipod_F,10);
            weap_xx(arifle_MSBS65_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_GL_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_EUDF35_erco_pointer_F,10);
            weap_xx(MMG_01_EUDF35_erco_pointer_snds_F,10);
            weap_xx(srifle_DMR_03_woodland_ams_pointer_snds_bipod_F,10);
            weap_xx(arifle_SPAR_01_EUDF35_erco_pointer_snds_F,10);
            weap_xx(hgun_Pistol_heavy_01_green_F,10);
            weap_xx(arifle_SPAR_02_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_SPAR_01_GL_khk_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_SPAR_03_khk_EUDF35_dms_pointer_snds_bipod_F,10);
            weap_xx(arifle_MSBS65_UBS_EUDF35_erco_pointer_snds_F,10);
            weap_xx(srifle_GM6_EUDF35_lrps_f,10);
            weap_xx(arifle_SDAR_F,10);
            weap_xx(hgun_Pistol_heavy_01_green_EUDF35_snds_F,10);
        };
        class TransportItems {
            item_xx(muzzle_snds_H_khk_F,10);
            item_xx(acc_pointer_IR,10);
            item_xx(optic_Arco_lush_F,10);
            item_xx(optic_Aco,10);
            item_xx(optic_ERCO_khk_F,10);
            item_xx(bipod_01_F_blk,10);
            item_xx(optic_DMS,10);
            item_xx(muzzle_snds_93mmg,10);
            item_xx(muzzle_snds_B_lush_F,10);
            item_xx(optic_AMS_khk,10);
            item_xx(muzzle_snds_m_khk_F,10);
            item_xx(muzzle_snds_B_khk_F,10);
            item_xx(optic_LRPS,10);
            item_xx(muzzle_snds_acp,10);
            item_xx(acc_flashlight_pistol,10);
            item_xx(optic_MRD_black,10);
        };
    };
    class IND_EUDF35_F_LaunchersBox : Box_NATO_WpsLaunch_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Launchers Box;
        class TransportMagazines {
            mag_xx(Titan_AA,5);
            mag_xx(Titan_AT,5);
            mag_xx(MRAWS_HEAT_F,5);
            mag_xx(NLAW_F,5);
        };
        class TransportWeapons {
            weap_xx(launch_B_Titan_olive_F,5);
            weap_xx(launch_B_Titan_short_tna_F,5);
            weap_xx(launch_MRAWS_green_F,5);
            weap_xx(launch_NLAW_F,5);
        };
        class TransportItems {
        };
    };
    class IND_EUDF35_F_UniformBox : Box_NATO_Uniforms_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Uniform Box;
        class TransportWeapons {
        };
        class TransportMagazines {
        };
        class TransportItems {
            item_xx(U_I_CombatUniform_EUDF35_Woodland,15);
            item_xx(U_I_EUDF35_HeliPilotCoveralls_Woodland,15);
            item_xx(U_I_EUDF35_pilotCoveralls,15);
            item_xx(U_I_EUDF35_OfficerUniform_Woodland,15);
            item_xx(U_I_EUDF35_Gorka_Woodland,15);
            item_xx(U_I_EUDF35_GhillieSuit_Woodland_1,15);
            item_xx(U_I_CombatUniform_Recon_EUDF35_Woodland,15);
            item_xx(U_I_EUDF35_FullGhillieSuit_Woodland,15);
            item_xx(U_I_EUDF35_Wetsuit,15);
        };
    };
    class IND_EUDF35_F_SupportBox : Box_NATO_Support_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Support Box;
        class TransportWeapons {
        };
        class TransportMagazines {
        };
        class TransportItems {
            item_xx(V_CarrierRigKBT_01_EUDF35_Woodland,10);
            item_xx(H_HelmetB_camo_EUDF35_woodland,10);
            item_xx(H_HelmetB_light_EUDF35_woodland,10);
            item_xx(H_HelmetB_light_EUDF35_woodland_1,10);
            item_xx(G_Balaclava_combat_EUDF35_green,10);
            item_xx(NVGoggles_INDEP,10);
            item_xx(ItemMap,10);
            item_xx(ItemCompass,10);
            item_xx(ItemWatch,10);
            item_xx(ItemRadio,10);
            item_xx(H_Cap_EUDF35_woodland_hs,10);
            item_xx(G_Tactical_Clear_EUDF35,10);
            item_xx(V_CarrierRigKBT_01_vest_EUDF35_Woodland,10);
            item_xx(H_HelmetCrew_EUDF35_woodland,10);
            item_xx(B_TacticalPack_EUDF35_woodland,10);
            item_xx(V_CarrierRigKBT_01_heavy_EUDF35_Woodland,10);
            item_xx(B_Carryall_EUDF35_woodland,10);
            item_xx(H_PilotHelmetHeli_I_E,10);
            item_xx(H_CrewHelmetHeli_I_E,10);
            item_xx(H_PilotHelmetFighter_B,10);
            item_xx(B_Parachute,10);
            item_xx(G_Combat_Goggles_tna_F_EUDF35,10);
            item_xx(Rangefinder,10);
            item_xx(Binocular,10);
            item_xx(G_Bandanna_oli_EUDF35,10);
            item_xx(ItemGPS,10);
            item_xx(H_Beret_gen_EUDF35,10);
            item_xx(I_EUDF35_UAV_01_backpack_F,10);
            item_xx(I_UavTerminal,10);
            item_xx(I_EUDF35_UAV_06_backpack_F,10);
            item_xx(I_EUDF35_UAV_06_medical_backpack_F,10);
            item_xx(I_HMG_01_weapon_F,10);
            item_xx(I_GMG_01_weapon_F,10);
            item_xx(I_HMG_01_support_F,10);
            item_xx(I_Mortar_01_weapon_F,10);
            item_xx(G_Balaclava_oli_EUDF35,10);
            item_xx(I_Mortar_01_support_F,10);
            item_xx(I_EUDF35_HMG_01_A_weapon_F,10);
            item_xx(I_EUDF35_GMG_01_A_weapon_F,10);
            item_xx(B_RadioBag_01_EUDF35_woodland,10);
            item_xx(V_Chestrig_EUDF35_Woodland_1,10);
            item_xx(H_Booniehat_EUDF35_woodland_1_hs,10);
            item_xx(H_MilCap_EUDF35_woodland_1,10);
            item_xx(Laserdesignator_03,10);
            item_xx(H_Cap_EUDF35_woodland_1_hs,10);
            item_xx(I_EUDF35_Static_Designator_01_weapon_F,10);
            item_xx(V_CarrierRigKBT_01_EUDF35_Woodland_1,10);
            item_xx(H_HelmetB_light_EUDF35_woodland_1,10);
            item_xx(B_AssaultPack_EUDF35_woodland_1,10);
            item_xx(H_HelmetHBK_headset_EUDF35_woodland_1,10);
            item_xx(V_RebreatherIA,10);
            item_xx(G_I_Diving,10);
            item_xx(B_Assault_Diver,10);
        };
    };
    class IND_EUDF35_F_SupplyBox : B_SupplyCrate_F {
        author = ALiVE ORBAT CREATOR;
        displayName = EUDF Supply Box;
        class TransportMagazines {
            mag_xx(30Rnd_65x39_caseless_msbs_mag,50);
            mag_xx(Chemlight_blue,50);
            mag_xx(16Rnd_9x21_Mag,50);
            mag_xx(HandGrenade,50);
            mag_xx(SmokeShell,50);
            mag_xx(SatchelCharge_Remote_Mag,50);
            mag_xx(DemoCharge_Remote_Mag,50);
            mag_xx(APERSBoundingMine_Range_Mag,50);
            mag_xx(APERSMine_Range_Mag,50);
            mag_xx(ClaymoreDirectionalMine_Remote_Mag,50);
            mag_xx(SLAMDirectionalMine_Wire_Mag,50);
            mag_xx(30Rnd_9x21_Mag_SMG_02,50);
            mag_xx(SmokeShellBlue,50);
            mag_xx(SmokeShellPurple,50);
            mag_xx(SmokeShellOrange,50);
            mag_xx(MiniGrenade,50);
            mag_xx(1Rnd_HE_Grenade_shell,50);
            mag_xx(MRAWS_HEAT_F,50);
            mag_xx(200Rnd_65x39_cased_Box,50);
            mag_xx(Titan_AA,50);
            mag_xx(150Rnd_93x64_Mag,50);
            mag_xx(Titan_AT,50);
            mag_xx(1Rnd_Smoke_Grenade_shell,50);
            mag_xx(1Rnd_SmokeGreen_Grenade_shell,50);
            mag_xx(1Rnd_SmokeOrange_Grenade_shell,50);
            mag_xx(1Rnd_SmokePurple_Grenade_shell,50);
            mag_xx(SmokeShellGreen,50);
            mag_xx(30Rnd_65x39_caseless_msbs_mag_Tracer,50);
            mag_xx(I_IR_Grenade,50);
            mag_xx(1Rnd_SmokeBlue_Grenade_shell,50);
            mag_xx(APERSMineDispenser_Mag,50);
            mag_xx(APERSTripMine_Wire_Mag,50);
            mag_xx(20Rnd_762x51_Mag,50);
            mag_xx(ATMine_Range_Mag,50);
            mag_xx(30Rnd_556x45_Stanag_green,50);
            mag_xx(11Rnd_45ACP_Mag,50);
            mag_xx(NLAW_F,50);
            mag_xx(150Rnd_556x45_Drum_Mag_F,50);
            mag_xx(30Rnd_556x45_Stanag_Tracer_Green,50);
            mag_xx(Laserbatteries,50);
            mag_xx(SmokeShellYellow,50);
            mag_xx(6Rnd_12Gauge_Pellets,50);
            mag_xx(5Rnd_127x108_Mag,50);
            mag_xx(Chemlight_yellow,50);
            mag_xx(30Rnd_556x45_Stanag,50);
            mag_xx(20Rnd_556x45_UW_mag,50);
            mag_xx(30Rnd_556x45_Stanag_red,50);
        };
        class TransportWeapons {
            weap_xx(arifle_MSBS65_EUDF35_arco_pointer_snds_F,10);
            weap_xx(hgun_P07_blk_F,10);
            weap_xx(arifle_MSBS65_EUDF35_aco_pointer_F,10);
            weap_xx(arifle_MSBS65_EUDF35_aco_pointer_snds_F,10);
            weap_xx(SMG_05_EUDF35_aco_pointer_F,10);
            weap_xx(LMG_Mk200_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_GL_EUDF35_arco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_Mark_EUDF35_dms_pointer_snds_bipod_F,10);
            weap_xx(arifle_MSBS65_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_GL_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_MSBS65_EUDF35_erco_pointer_F,10);
            weap_xx(MMG_01_EUDF35_erco_pointer_snds_F,10);
            weap_xx(srifle_DMR_03_woodland_ams_pointer_snds_bipod_F,10);
            weap_xx(arifle_SPAR_01_EUDF35_erco_pointer_snds_F,10);
            weap_xx(hgun_Pistol_heavy_01_green_F,10);
            weap_xx(arifle_SPAR_02_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_SPAR_01_GL_khk_EUDF35_erco_pointer_snds_F,10);
            weap_xx(arifle_SPAR_03_khk_EUDF35_dms_pointer_snds_bipod_F,10);
            weap_xx(arifle_MSBS65_UBS_EUDF35_erco_pointer_snds_F,10);
            weap_xx(srifle_GM6_EUDF35_lrps_f,10);
            weap_xx(arifle_SDAR_F,10);
            weap_xx(hgun_Pistol_heavy_01_green_EUDF35_snds_F,10);
            weap_xx(launch_B_Titan_olive_F,10);
            weap_xx(launch_B_Titan_short_tna_F,10);
            weap_xx(launch_MRAWS_green_F,10);
            weap_xx(launch_NLAW_F,10);
        };
        class TransportItems {
            item_xx(muzzle_snds_H_khk_F,10);
            item_xx(acc_pointer_IR,10);
            item_xx(optic_Arco_lush_F,10);
            item_xx(optic_Aco,10);
            item_xx(optic_ERCO_khk_F,10);
            item_xx(bipod_01_F_blk,10);
            item_xx(optic_DMS,10);
            item_xx(muzzle_snds_93mmg,10);
            item_xx(muzzle_snds_B_lush_F,10);
            item_xx(optic_AMS_khk,10);
            item_xx(muzzle_snds_m_khk_F,10);
            item_xx(muzzle_snds_B_khk_F,10);
            item_xx(optic_LRPS,10);
            item_xx(muzzle_snds_acp,10);
            item_xx(acc_flashlight_pistol,10);
            item_xx(optic_MRD_black,10);
            item_xx(V_CarrierRigKBT_01_EUDF35_Woodland,10);
            item_xx(H_HelmetB_camo_EUDF35_woodland,10);
            item_xx(H_HelmetB_light_EUDF35_woodland,10);
            item_xx(H_HelmetB_light_EUDF35_woodland_1,10);
            item_xx(G_Balaclava_combat_EUDF35_green,10);
            item_xx(NVGoggles_INDEP,10);
            item_xx(ItemMap,10);
            item_xx(ItemCompass,10);
            item_xx(ItemWatch,10);
            item_xx(ItemRadio,10);
            item_xx(H_Cap_EUDF35_woodland_hs,10);
            item_xx(G_Tactical_Clear_EUDF35,10);
            item_xx(V_CarrierRigKBT_01_vest_EUDF35_Woodland,10);
            item_xx(H_HelmetCrew_EUDF35_woodland,10);
            item_xx(B_TacticalPack_EUDF35_woodland,10);
            item_xx(V_CarrierRigKBT_01_heavy_EUDF35_Woodland,10);
            item_xx(B_Carryall_EUDF35_woodland,10);
            item_xx(H_PilotHelmetHeli_I_E,10);
            item_xx(H_CrewHelmetHeli_I_E,10);
            item_xx(H_PilotHelmetFighter_B,10);
            item_xx(B_Parachute,10);
            item_xx(G_Combat_Goggles_tna_F_EUDF35,10);
            item_xx(Rangefinder,10);
            item_xx(Binocular,10);
            item_xx(G_Bandanna_oli_EUDF35,10);
            item_xx(ItemGPS,10);
            item_xx(H_Beret_gen_EUDF35,10);
            item_xx(I_EUDF35_UAV_01_backpack_F,10);
            item_xx(I_UavTerminal,10);
            item_xx(I_EUDF35_UAV_06_backpack_F,10);
            item_xx(I_EUDF35_UAV_06_medical_backpack_F,10);
            item_xx(I_HMG_01_weapon_F,10);
            item_xx(I_GMG_01_weapon_F,10);
            item_xx(I_HMG_01_support_F,10);
            item_xx(I_Mortar_01_weapon_F,10);
            item_xx(G_Balaclava_oli_EUDF35,10);
            item_xx(I_Mortar_01_support_F,10);
            item_xx(I_EUDF35_HMG_01_A_weapon_F,10);
            item_xx(I_EUDF35_GMG_01_A_weapon_F,10);
            item_xx(B_RadioBag_01_EUDF35_woodland,10);
            item_xx(V_Chestrig_EUDF35_Woodland_1,10);
            item_xx(H_Booniehat_EUDF35_woodland_1_hs,10);
            item_xx(H_MilCap_EUDF35_woodland_1,10);
            item_xx(Laserdesignator_03,10);
            item_xx(H_Cap_EUDF35_woodland_1_hs,10);
            item_xx(I_EUDF35_Static_Designator_01_weapon_F,10);
            item_xx(V_CarrierRigKBT_01_EUDF35_Woodland_1,10);
            item_xx(H_HelmetB_light_EUDF35_woodland_1,10);
            item_xx(B_AssaultPack_EUDF35_woodland_1,10);
            item_xx(H_HelmetHBK_headset_EUDF35_woodland_1,10);
            item_xx(V_RebreatherIA,10);
            item_xx(G_I_Diving,10);
            item_xx(B_Assault_Diver,10);
            item_xx(U_I_CombatUniform_EUDF35_Woodland,10);
            item_xx(U_I_EUDF35_HeliPilotCoveralls_Woodland,10);
            item_xx(U_I_EUDF35_pilotCoveralls,10);
            item_xx(U_I_EUDF35_OfficerUniform_Woodland,10);
            item_xx(U_I_EUDF35_Gorka_Woodland,10);
            item_xx(U_I_EUDF35_GhillieSuit_Woodland_1,10);
            item_xx(U_I_CombatUniform_Recon_EUDF35_Woodland,10);
            item_xx(U_I_EUDF35_FullGhillieSuit_Woodland,10);
            item_xx(U_I_EUDF35_Wetsuit,10);
        };
    };
